name: TradingView Scraper

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '0 */6 * * *'  # Re-trigger every 6 hours (if it times out or finishes)


jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client tradingview_ta apscheduler Flask

    - name: Run scraper
      env:
        GOOGLE_SHEETS_API_KEY: ${{ secrets.PROJECT_MALAGA_KEY }}
      run: |
        echo "$GOOGLE_SHEETS_API_KEY" > /tmp/service-account.json
        python updater.py
