name: Update Google Sheet with Stocktwits Trending Stocks

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
